config/routes.rb
Webrent::Application.routes.draw do
  match '/forgot_password', to:'users#forgot_password', via: 'post'
  resources :users, except: [:index,:show,:update,:destroy,:edit,:new,:create] do
    member do
      match '/register', to:'users#register', via: 'get'
      match '/reset_password', to:'users#reset_password', via: 'get'
      match '/update_password', to:'users#update_password', via: 'patch'
    end
  end

  resources :administrators, only: [:index] do
    collection do
      resources :users do
        collection do
          get 'fill_permission', to: 'users#fill_permission'
          get 'fill_status', to: 'users#fill_status'
        end
      end
    end
  end

  post 'update_permission_user', to: 'users#update_permission'
  post 'update_status_user', to: 'users#update_status'

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#signup',            via: 'get'
  match '/signup_access',  to: 'users#signup_access',            via: 'post'
  match '/signup_access',  to: 'static_pages#signup_access',            via: 'post'
  match '/welcome',  to: 'static_pages#welcome',via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/models/user.rb
class User < ActiveRecord::Base
	before_save { self.email = email.downcase }
	before_create :set_sid
	has_many :website

	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence:   true,
	format:     { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }, :if => :validate_password?
	validates :password_confirmation, presence: true, :if => :validate_password?
	
	def User.new_remember_token
		SecureRandom.urlsafe_base64
	end

	def User.encrypt(token)
		Digest::SHA1.hexdigest(token.to_s)
	end

	def to_secure_param
		self.sid
	end

	def set_sid
		begin
			secure = SecureRandom.urlsafe_base64
		end while !User.find_by_sid(secure).nil?
		if self.new_record?
			self.sid = secure
		else
			self.update_column("sid", secure)
		end
	end

	def validate_password?
		password.present? || password_confirmation.present?
	end

	private

	def create_remember_token
		self.remember_token = User.encrypt(User.new_remember_token)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :correct_user, except: [:register,:forgot_password,:reset_password,:update_password,:signup,:signup_access]
	before_filter :correct_admin, except: [:register,:forgot_password,:reset_password,:update_password,:signup,:signup_access]
	before_filter :correct_signup, only: [:signup]


	def new
		@user = User.new
	end

	def edit
		@user = User.find(params[:id])
	end

	def create
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Thêm tài khoản <b>#{@user.email}</b> thành công.".html_safe
			redirect_to users_path
		else
			render 'new'
		end
	end

	def update_permission
		users_id = params[:users_id].split(" ")
		users_id.each do |user_id|
			@user = User.find(user_id)
			@user.update_attribute("admin",params[:admin])
		end
	end

	def update_status
		users_id = params[:users_id].split(" ")
		users_id.each do |user_id|
			@user = User.find(user_id)
			@user.update_attribute("active",params[:status])
		end
	end

	def fill_permission
		if params[:a] == "true"
			admin = true
		else
			admin = false
		end
		@users = User.where(admin: admin,smod: false).paginate(:page => params[:page], :per_page => 10)
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			flash[:success] = "Sửa tài khoản <b>#{@user.email}</b> thành công.".html_safe
			redirect_to users_path
		else
			render 'edit'
		end
	end

	def destroy
		messeage = "Đã xóa thành công các tài khoản: <br>"
		users_id = params[:users_id].split(" ")
		users_id.each do |user_id|
			@user = User.find(user_id)
			@user.destroy
			messeage += " - <b>#{@user.email}</b> <br>"
		end
		flash[:success] = messeage.html_safe
	end

	def index
		all_users = User.all.order("id desc")
		users = []
		all_users.each do |user|
			if current_user.smod
				if !user.smod
					users << user
				end
			else
				if !user.admin
					users << user
				end
			end
		end
		@count = users.count
		@users = users.paginate(:page => params[:page], :per_page => 10)
	end

	def register
		@user = User.find_by_sid(params[:id])
		if @user.nil?
			flash[:success] = "Tài khoản của bạn đã được kích hoạt. Bạn có thể login vào website của chúng tôi ngay bây giờ."
			redirect_to signin_path
		else
			if @user.update_attribute(:active, true)
				flash[:success] = "Tài khoản của bạn đã được kích hoạt. Bạn có thể login vào website của chúng tôi ngay bây giờ."
				@user.set_sid
				redirect_to signin_path
			end
		end
	end

	def forgot_password
		@user = User.find_by_email(params[:email])
		unless @user.nil?
			@user.update_attribute(:reset,false)
			@user.update_attribute(:send_reset_at,Time.zone.now)
			Mailer.forgot_password(@user).deliver
		end
	end

	def reset_password
		@user = User.find_by_sid(params[:id])
		if @user.nil? || @user.reset || @user.send_reset_at < 1.days.ago
			flash[:danger] = "Lấy lại mật khẩu đã hết hiệu lực. Hãy thử lại."
			redirect_to signin_path
		end
	end

	def update_password
		@user = User.find(params[:id])
		@user.update_attribute(:reset,true)
		@user.set_sid
		if @user.update_attributes(user_params)
			flash[:success] = "Đổi mật khẩu thành công. Bạn có thể đăng nhập vào website ngay bây giờ."
			redirect_to signin_path
		else
			render 'reset_password'
		end
	end

	def signup
		@user = User.new
	end

	def signup_access
		@user = User.new(user_params)
		if @user.save
			flash[:success] = "Bạn đã đăng ký tài khoản Webrent thành công. Hãy kiểm tra email và kích hoạt tài khoản ngay bây giờ."
			Mailer.registration_confirmation(@user).deliver
			redirect_to signin_path
		else
			render 'signup'
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password,:password_confirmation,:active,:admin)
	end

	def correct_user
    	redirect_to(root_path) if current_user.nil?
	end

	def correct_signup
    	redirect_to edit_user_path(current_user) if !current_user.nil?
	end

	def correct_admin
		redirect_to(root_path) unless current_user.admin
	end

end

app/helpers/users_helper.rb
module UsersHelper
	def status_label(status)
		if status == true
			return "<span class='label label-primary'>Đã kích hoạt</span>"
		else
			return "<span class='label label-webrent'>Chưa kích hoạt</span>"
		end
	end

	def admin_label(admin,smod)
		if admin == true
			return "<span class='label label-success'>Quản trị viên</span>" if smod == false
			return "<span class='label label-danger'>Siêu quản trị</span>" if smod == true
		else
			return "<span class='label label-warning'>Người dùng</span>"
		end
	end

	def gender_error(msg)
		if msg == "Name can't be blank"
			return "Họ và tên không được để trống"
		elsif msg == "Email can't be blank"
			return "Địa chỉ email không được để trống"
		elsif msg == "Email is invalid"
			return "Địa chỉ email không đúng định dạng"
		elsif msg == "Password can't be blank"
			return "Mật khẩu không được để trống"
		elsif msg == "Password is too short (minimum is 6 characters)"
			return "Mật khẩu quá ngắn (cần ít nhất 6 kí tự)"
		elsif msg == "Email has already been taken"
			return "Địa chỉ email đã được đăng ký, hãy thử email khác"
		else
			return "Nhập lại mật khẩu không khớp"
		end
	end
end

app/views/users/_form.html.erb
<%= form_for @user,html: {class: "form-horizontal"} do |f| %>
<%= render 'shared/error_messages', object: @user %>
<div class="form-group">
	<%= f.label "Họ và tên* :", class: "col-lg-3 control-label" %>
	<div class="col-lg-9">
		<%= f.text_field :name, style:"margin-bottom: 20px;",class: "form-control" %>
	</div>
	<%= f.label "Địa chỉ email* :", class: "col-lg-3 control-label" %>
	<div class="col-lg-9">
		<%= f.text_field :email, style:"margin-bottom: 20px;",class: "form-control" %>
	</div>
	<%= f.label "Mật khẩu* :", class: "col-lg-3 control-label" %>
	<div class="col-lg-9">
		<%= f.password_field :password, style:"margin-bottom: 20px;",class: "form-control" %>
	</div>
	<%= f.label "Nhập lại mật khẩu* :", class: "col-lg-3 control-label" %>
	<div class="col-lg-9">
		<%= f.password_field :password_confirmation, style:"margin-bottom: 25px;",class: "form-control" %>
	</div>
	<%= f.label "Trạng thái :", class: "col-lg-3 control-label" %>
	<div class="col-lg-9">
		<%= f.select :active, [['Chưa kích hoạt', false], ['Đã kích hoạt', true]],{},class: "form-control", style:"margin-bottom: 20px;" %>
	</div>
	<% if current_user.smod %>
		<%= f.label "Phân quyền :", class: "col-lg-3 control-label" %>
		<div class="col-lg-9">
			<%= f.select :admin, [['Người dùng', false], ['Quản trị viên', true]],{},class: "form-control", style:"margin-bottom: 25px;" %>
		</div>
	<% end %>
	<div class="col-lg-3">
	</div>
	<div class="col-lg-9">
		<%= f.button :submit, class: "btn btn-lg btn-webrent",style: "width:150px" do %>
		<span style='margin-right:10px' class='glyphicon glyphicon-ok-circle' ></span> Đồng ý
		<% end %>
		<%= link_to raw("<span style='margin-right:10px' class='glyphicon glyphicon-circle-arrow-left' ></span> Quay lại"), users_path, class: "btn btn-primary btn-lg",style: "width:150px;margin-left:5px" %>
	</div>
</div>
<% end %>

app/views/users/_user.html.erb
<tr id="<%=user.id%>" class="rows">
	<td style="text-align:center" class="check">
		<input type="checkbox" class="checkall" name="user_ids" value="<%= user.id %>" />
	</td>
	<td><%= link_to user.email, edit_user_path(user) %></td>
	<td><%= user.name %></td>
	<td><center><%= raw(admin_label(user.admin,user.smod)) %></center></td>
	<td><center><%= raw(status_label(user.active)) %></center></td>
</tr>

app/views/users/_user_navigation.html.erb
<div class="row">
		<div class="col-md-8">
			<div class="btn-group">
				<button type="button" id="mark-all" class="btn btn-inline-inverse"><span style='margin-right:10px' class='glyphicon glyphicon-ok-circle'></span> Chọn tất cả</button>
				<% if current_user.smod %>
				<%= button_tag raw("<span style='margin-right:10px' class='glyphicon glyphicon-trash'></span> Xóa"), class: "btn btn-inline-inverse", id: "delete-mark", style: "display:none" %>
				<% end %>
				<div class="btn-group">
					<button type="button" id="edit-mark" class="btn btn-inline-inverse dropdown-toggle" style="display:none" data-toggle="dropdown">
						<span style='margin-right:10px' class='glyphicon glyphicon-pencil'></span> Chỉnh sửa
						<span class="caret" style='margin-left:10px'></span>
					</button>
					<ul class="dropdown-menu">
						<% if current_user.smod %>
						<li><a id="admin" class="permission" href="#"><b>Phân quyền: </b>Quản trị viên</a></li>
						<li><a id="user" class="permission" href="#"><b>Phân quyền: </b>Người dùng</a></li>
						<li class="divider"></li>
						<% end %>
						<li><a id="active" class="status" href="#"><b>Trạng thái: </b>Đã kích hoạt</a></li>
						<li><a id="suppend" class="status" href="#"><b>Trạng thái: </b>Chưa kích hoạt</a></li>
					</ul>
				</div>
				<div class="btn-group">
					<button type="button" class="btn btn-inline-inverse dropdown-toggle" data-toggle="dropdown">
						<span style='margin-right:10px' class='glyphicon glyphicon-filter'></span> Lọc
						<span class="caret" style='margin-left:5px'></span>
					</button>
					<ul class="dropdown-menu">
						<% if current_user.smod %>
						<li><a id="fill-admin" class="fill-permission" href="#fill-admin"><b>Phân quyền: </b>Quản trị viên</a></li>
						<li><a id="fill-user" class="fill-permission" href="#fill-user"><b>Phân quyền: </b>Người dùng</a></li>
						<li class="divider"></li>
						<% end %>
						<li><a id="fill-active" class="fill-status" href="#"><b>Trạng thái: </b>Đã kích hoạt</a></li>
						<li><a id="fill-suppend" class="fill-status" href="#"><b>Trạng thái: </b>Chưa kích hoạt</a></li>
					</ul>
				</div>
				<%= link_to raw("<span style='margin-right:10px' class='glyphicon glyphicon-refresh'></span> Làm mới"), users_path, class: "btn btn-inline-inverse" %>
			</div>
		</div>
		<div class="col-md-4 pull-right">
			<div class="input-group">
				<input type="text" class="form-control" placeholder="Nhập vào họ tên hoặc địa chỉ email...">
				<span class="input-group-btn">
					<button class="btn btn-inline-inverse" type="button"><span class="glyphicon glyphicon-search"></span></button>
				</span>
			</div><!-- /input-group -->
		</div>
	</div>

app/views/users/destroy.js.erb
window.location.reload(true);

app/views/users/edit.html.erb
<% provide(:title, 'Quản lý tài khoản') %>
<div class="col-md-11 col-md-offset-2">
	<h1 class="page-header" style="font-size:45px"><a href = "<%= users_path %>"><b><span class='glyphicon glyphicon-user'></span> Quản lý tài khoản </b></a> <span style="font-size:30px;color:#999999"> Sửa tài khoản</span></h1>
	<br>
	<div class="row">
		<div class="col-md-8">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/users/fill_permission.html.erb
<% provide(:title, 'Quản lý tài khoản') %>
<div class="col-md-11 col-md-offset-2">
	<h1 class="page-header" style="font-size:45px"><a href = "<%= users_path %>"><b><span class='glyphicon glyphicon-user'></span> Quản lý tài khoản </b></a><strong><small>(Tổng cộng: <%= @count %>)</small></strong> <%= link_to raw("<span style='margin-right:10px' class='glyphicon glyphicon-plus-sign'></span> Thêm tài khoản"),new_user_path, class: "pull-right btn-lg btn btn-outline-webrent",style: "margin-top:10px" %></h1>
	<hr>
	<%= render 'user_navigation' %>
	<br>
	<table class="table table-hover table-users">
		<thead>
			<tr>
				<th>
					<center><b><span class="glyphicon glyphicon-ok-circle"></span></b></center>
				</th>
				<th><b>Địa chỉ email</b></th>
				<th><b>Họ và tên</b></th>
				<th><center><b>Phân quyền</b></center></th>
				<th><center><b>Trạng thái</b></center></th>
			</tr>
		</thead>
		<tbody id="data-users">
			<% @users.each do |user| %>
			<%= render "user", user: user %>
			<% end %>
		</tbody>
	</table>
	<div id="page-pagination">
		<%= will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
	</div>
</div>
<script type="text/javascript">
var check_click = true;
$(".check").hover(function(){
	check_click = false;
},function(){
	check_click = true;
});

$('.rows').click(function(){
	var id = $(this).attr("id");
	if(check_click)
		window.location.href=id+'/edit';
})


var mark_all_click = false
$("#mark-all").click(function(){
	if(!mark_all_click)
	{
		$("#delete-mark").css("display","inline")
		$("#edit-mark").css("display","inline")
		$('input:checkbox.checkall').prop('checked','checked')
		$(this).html("<span style='margin-right:10px' class='glyphicon glyphicon-remove-circle'></span> Hủy bỏ")
		mark_all_click = true
	}
	else
	{
		$("#delete-mark").css("display","none")
		$("#edit-mark").css("display","none")
		$('input:checkbox.checkall').removeAttr('checked')
		$(this).html("<span style='margin-right:10px' class='glyphicon glyphicon-ok-circle'></span> Chọn tất cả")
		mark_all_click = false
	}
})
function check_all()
{
	check = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			check = true
		}
	})
	return check
}
$(".checkall").click(function(){
	if(check_all())
	{
		$("#delete-mark").css("display","inline")
		$("#edit-mark").css("display","inline")
		$("#mark-all").html("<span class='glyphicon glyphicon-remove-circle'></span> Hủy bỏ")
		mark_all_click = true
	}
	else
	{
		$("#delete-mark").css("display","none")
		$("#edit-mark").css("display","none")
		$("#mark-all").html("<span class='glyphicon glyphicon-ok-circle'></span> Chọn tất cả")
		mark_all_click = false

	}
})

$("#delete-mark").click(function(){
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn xóa các tài khoản được đánh dấu?"))
		{
			$.ajax({ type: "DELETE",   
				url: "<%= user_path(User.first) %>",   
				data: {users_id:users_id} ,
			});
		}
	}
})

$(".permission").click(function(){
	var permission = $(this).attr("id")
	var messeage = ""
	var admin
	if(permission == "admin")
	{
		messeage = "\"Quản trị viên\""
		admin = true;
	}
	else
	{
		messeage = "\"Người dùng\""
		admin = false
	}
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){	
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn các tài khoản được đánh dấu sẽ trở thành "+messeage+"?"))
		{
			$.ajax({ type: "POST",   
				url: "<%= update_permission_user_path %>",   
				data: {users_id:users_id,admin: admin} ,
			});
		}
	}
})

$(".status").click(function(){
	var status = $(this).attr("id")
	var messeage = ""
	var status
	if(status == "active")
	{
		messeage = "\"Đã kích hoạt\""
		status = true;
	}
	else
	{
		messeage = "\"Chưa kích hoạt\""
		status = false
	}
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn trạng thái của các tài khoản được đánh dấu sẽ trở thành "+messeage+"?"))
		{
			$.ajax({ type: "POST",   
				url: "<%= update_status_user_path %>",   
				data: {users_id:users_id,status: status} ,
			});
		}
	}
})
$(".fill-permission").click(function(){
	var permission = $(this).attr("id")
	var admin
	if(permission == "fill-admin")
	{
		admin = true;
	}
	else
	{
		admin = false
	}
	window.location.href='fill_permission?a='+admin;
})
</script>

app/views/users/forgot_password.js.erb
<% if @user.nil? %>
$("#alert-danger").css("display","block")
<% else %>
$("#alert-danger").css("display","none")
$("#alert").css("display","block")
$("#reset-password").css("display","none")
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Quản lý tài khoản') %>
<div class="col-md-11 col-md-offset-2">
	<h1 class="page-header" style="font-size:45px"><a href = "<%= users_path %>"><b><span class='glyphicon glyphicon-user'></span> Quản lý tài khoản </b></a><strong><small>(Tổng cộng: <%= @count %>)</small></strong> <%= link_to raw("<span style='margin-right:10px' class='glyphicon glyphicon-plus-sign'></span> Thêm tài khoản"),new_user_path, class: "pull-right btn-lg btn btn-outline-webrent-active",style: "margin-top:10px" %></h1>
	<% if @users.any? %>
	<br>
	<%= render 'user_navigation' %>
	<br>
	<table class="table table-hover table-users">
		<thead>
			<tr>
				<th>
					<center><b><span class="glyphicon glyphicon-ok-circle"></span></b></center>
				</th>
				<th><b>Địa chỉ email</b></th>
				<th><b>Họ và tên</b></th>
				<th><center><b>Phân quyền</b></center></th>
				<th><center><b>Trạng thái</b></center></th>
			</tr>
		</thead>
		<tbody id="data-users">
			<% @users.each do |user| %>
			<%= render "user", user: user %>
			<% end %>
		</tbody>
	</table>
	<div id="page-pagination">
		<%= will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3 %>
	</div>
	<% end %>
</div>
<script type="text/javascript">
var check_click = true;
$(".check").hover(function(){
	check_click = false;
},function(){
	check_click = true;
});

$('.rows').click(function(){
	var id = $(this).attr("id");
	if(check_click)
		window.location.href='users/'+id+'/edit';
})


var mark_all_click = false
$("#mark-all").click(function(){
	if(!mark_all_click)
	{
		$("#delete-mark").css("display","inline")
		$("#edit-mark").css("display","inline")
		$('input:checkbox.checkall').prop('checked','checked')
		$(this).html("<span style='margin-right:10px' class='glyphicon glyphicon-remove-circle'></span> Hủy bỏ")
		mark_all_click = true
	}
	else
	{
		$("#delete-mark").css("display","none")
		$("#edit-mark").css("display","none")
		$('input:checkbox.checkall').removeAttr('checked')
		$(this).html("<span style='margin-right:10px' class='glyphicon glyphicon-ok-circle'></span> Chọn tất cả")
		mark_all_click = false
	}
})
function check_all()
{
	check = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			check = true
		}
	})
	return check
}
$(".checkall").click(function(){
	if(check_all())
	{
		$("#delete-mark").css("display","inline")
		$("#edit-mark").css("display","inline")
		$("#mark-all").html("<span class='glyphicon glyphicon-remove-circle'></span> Hủy bỏ")
		mark_all_click = true
	}
	else
	{
		$("#delete-mark").css("display","none")
		$("#edit-mark").css("display","none")
		$("#mark-all").html("<span class='glyphicon glyphicon-ok-circle'></span> Chọn tất cả")
		mark_all_click = false

	}
})

$("#delete-mark").click(function(){
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn xóa các tài khoản được đánh dấu?"))
		{
			$.ajax({ type: "DELETE",   
				url: "<%= user_path(User.first) %>",   
				data: {users_id:users_id} ,
			});
		}
	}
})

$(".permission").click(function(){
	var permission = $(this).attr("id")
	var messeage = ""
	var admin
	if(permission == "admin")
	{
		messeage = "\"Quản trị viên\""
		admin = true;
	}
	else
	{
		messeage = "\"Người dùng\""
		admin = false
	}
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn các tài khoản được đánh dấu sẽ trở thành "+messeage+"?"))
		{
			$.ajax({ type: "POST",   
				url: "<%= update_permission_user_path %>",   
				data: {users_id:users_id,admin: admin} ,
			});
		}
	}
})

$(".status").click(function(){
	var status = $(this).attr("id")
	var messeage = ""
	var status
	if(status == "active")
	{
		messeage = "\"Đã kích hoạt\""
		status = true;
	}
	else
	{
		messeage = "\"Chưa kích hoạt\""
		status = false
	}
	var users_id = ""
	var sub_checked = false
	$(".table-users tr").each(function(){
		if($(this).children().children(".checkall").is(':checked'))
		{
			users_id += $(this).children().children(".checkall").val() +" "
			sub_checked = true
		}
	})
	if (sub_checked)
	{
		if (confirm("Bạn chắc chắn trạng thái của các tài khoản được đánh dấu sẽ trở thành "+messeage+"?"))
		{
			$.ajax({ type: "POST",   
				url: "<%= update_status_user_path %>",   
				data: {users_id:users_id,status: status} ,
			});
		}
	}
})

$(".fill-permission").click(function(){
	var permission = $(this).attr("id")
	var admin
	if(permission == "fill-admin")
	{
		admin = true;
	}
	else
	{
		admin = false
	}
	window.location.href='users/fill_permission?a='+admin;
})
</script>

app/views/users/new.html.erb
<% provide(:title, 'Quản lý tài khoản') %>
<div class="col-md-11 col-md-offset-2">
	<h1 class="page-header" style="font-size:45px"><a href = "<%= users_path %>"><b><span class='glyphicon glyphicon-user'></span> Quản lý tài khoản </b></a> <span style="font-size:30px;color:#999999"> Thêm tài khoản</span></h1>
	<br>
	<div class="row">
		<div class="col-md-8">
			<%= render 'form' %>
		</div>
	</div>
</div>

app/views/users/reset_password.html.erb
<% provide(:title, "Khôi phục mật khẩu") %>
<div class="row">
  <div class="col-xs-7 col-sm-7 col-md-7 col-xs-offset-3 col-sm-offset-3 col-md-offset-3" style="padding-top:50px">
    <div class="login">
      <div class="row-fluid pricing-table pricing-one-column">
        <div class="col-xs-10 col-sm-10 col-md-10 plan">
          <h2><b>Khôi phục mật khẩu</b></h2>
          <p>Nhập mật khẩu mới của bạn để hoàn tất lấy lại mật khẩu.</p>
          <br>
          <%= form_for @user,url: update_password_user_path(@user) do |f| %>
          <%= render 'shared/error_messages', object: @user %>

          <%= f.password_field :password,class: "form-control",placeholder:"Mật khẩu mới", style:"margin-bottom: 15px;" %>

          <%= f.password_field :password_confirmation,class: "form-control",placeholder:"Nhập lại mật khẩu mới", style:"margin-bottom: 20px;" %>

          <%= f.submit "Đổi mật khẩu", class: "btn btn-lg btn-webrent btn-block", style:"margin-bottom: 20px;" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/update_permission.js.erb
window.location.reload(true);

app/views/users/update_status.js.erb
window.location.reload(true);