config/routes.rb
Webrent::Application.routes.draw do
  match '/forgot_password', to:'users#forgot_password', via: 'post'
  resources :users, except: [:index,:show,:update,:destroy,:edit,:new,:create] do
    member do
      match '/register', to:'users#register', via: 'get'
      match '/reset_password', to:'users#reset_password', via: 'get'
      match '/update_password', to:'users#update_password', via: 'patch'
    end
  end

  resources :administrators, only: [:index] do
    collection do
      resources :users do
        collection do
          get 'fill_permission', to: 'users#fill_permission'
          get 'fill_status', to: 'users#fill_status'
        end
      end
    end
  end

  post 'update_permission_user', to: 'users#update_permission'
  post 'update_status_user', to: 'users#update_status'

  resources :sessions, only: [:new, :create, :destroy]
  root  'static_pages#home'
  match '/signup',  to: 'users#signup',            via: 'get'
  match '/signup_access',  to: 'users#signup_access',            via: 'post'
  match '/signup_access',  to: 'static_pages#signup_access',            via: 'post'
  match '/welcome',  to: 'static_pages#welcome',via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :sessions, only: [:new, :create, :destroy]

  

end

app/views/layouts/_dropdown_signin.html.erb
<a id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">Đăng nhập <strong class="caret"></strong></a>
<div class="sign-in dropdown-menu" role="menu" aria-labelledby="dLabel">
	<%= form_for(:session, url: sessions_path) do |f| %>
	<%=f.text_field :email, style:"margin-bottom: 15px;",class: "form-control",placeholder:"Email"%>
	<%=f.password_field :password, style:"margin-bottom: 15px;",class: "form-control",placeholder:"Mật khẩu"%>
	<%= f.submit "Đăng nhập", class: "btn btn-webrent btn-block", style:"margin-bottom: 10px;" %>
	<%= link_to "Quên mật khẩu", "#",class: "forgot btn btn-warning btn-block" %>
	<% end %>
	<br>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer clearfix">
	<div class="container">
		<center>
		<small>
			<p><a href="#" style="font-size:15px"><b>Webrent</b></a> design by <b>DungVT</b> - Địa chỉ: <b>Khâm Thiên, Đống Đa, TP.Hà Nội</b>  - Số điện thoại: <b>(+84)-1255921151</b> - Email liên hệ: <a href="#"><b>dungvt9691@gmail.com</b></a></p>
		</small>
		</center>
	</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-default navbar-fixed-top bs-docs-nav" role="banner">
  <div style="padding-left:20px;padding-right:20px">
    <div class="navbar-header">
      <a class="navbar-brand" href="<%=root_path %>" style="font-size:30px"><b>Webrent</b></a>
    </div>
    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
      <ul class="nav navbar-nav">
        
        <li class='<%= "active" if check_page()[0] == "welcome" %>'>
          <a style="width:130px" href="<%=welcome_path %>"><span style="padding-right:5px" class="glyphicon glyphicon-home"></span> Trang chủ</a>
        </li>
        
        <li class='<%= "active" if check_page()[0] == "intro" %>'>
          <a style="width:130px" href="#"><span style="padding-right:5px" class="glyphicon glyphicon-star"></span> Giới thiệu</a>
        </li>
        
        <li class='<%= "active" if check_page()[0] == "websites" %>'>
          <a style="width:190px" href="#"><span style="padding-right:5px" class="glyphicon glyphicon-list"></span> Danh sách website</a>
        </li>
        
        <li class='<%= "active" if check_page()[0] == "store" %>'>
          <a style="width:130px" href=""><span style="padding-right:5px" class="glyphicon glyphicon-shopping-cart"></span> Cửa hàng</a>
        </li>
        
        <li>
          <div id="custom-search-form" class="form-search form-horizontal">
            <div class="input-append">
              <input type="text" class="search-query form-control" placeholder="Từ khóa tìm kiếm...">
              <button class="btn btn-search"><img src="/assets/icons/search_1.png"></button>
            </div>
          </div>
      </li>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if signed_in? %>
        <li>
          <div class="btn-group" style="padding-top:8px">
            <button type="button" class="btn btn-outline-webrent-active" style="width:235px">Xin chào, <b><%= current_user.name.truncate(20) %></b></button>
            <button type="button" class="btn btn-outline-webrent-active dropdown-toggle" data-toggle="dropdown" style="height:33px">
              <span class="glyphicon glyphicon-cog"></span>
            </button>
            <ul class="dropdown-menu" role="menu" style="width:267px">
              <li><a href="#"><i class="glyphicon glyphicon-list" style="margin-right:10px"></i> Websites <span style="margin-left:10px" class="badge badge-primary">4</span></a></li>
              <li><a href="#"><i class="glyphicon glyphicon-shopping-cart" style="margin-right:10px"></i> Đơn hàng <span style="margin-left:10px" class="badge badge-primary">10</span></a></li>
              <li class="divider"></li>
              <li><a href="#"><i class="glyphicon glyphicon-user" style="margin-right:10px"></i> Thông tin cá nhân</a></li>
              <li><a href="#"><i class="glyphicon glyphicon-usd" style="margin-right:10px"></i> Nạp thẻ</a></li>
              <% if current_user.admin %>
              <li><a href="<%= users_path() %>" method="GET"><i class="glyphicon glyphicon-wrench" style="margin-right:10px"></i> Quản lý Webrent</a></li>
              <% end %>
              <li class="divider"></li>
              <li><%= link_to raw("<i class='glyphicon glyphicon-off' style='margin-right:10px'></i> Đăng xuất"), signout_path, method: "delete" %></li>
            </ul>
          </div>
        </li>
        <% else %>
        
        <li class='<%= "active" if check_page()[0] == "signup" %>'><%= link_to "Đăng ký", signup_path,style: "width:120px;text-align:center" %></li>
        
        <li class='<%= "active" if check_page()[0] == "signin" %>'>
          <%= link_to "Đăng nhập", signin_path,style: "width:120px;text-align:center" %>
        </li>
        
      </li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

app/views/layouts/_menu.html.erb
<% page = check_controller() %>
<div class="cbp-spmenu-push">
	<nav class="cbp-spmenu cbp-spmenu-vertical" id="cbp-spmenu-s1">
		<h3><a style="color:#fff;font-size:30px;margin-right:10px"><b>Trang Quản Trị</b></a> 
		<a href="<%= welcome_path %>"><img src="/assets/pages/icon.png" height="30px" class="icon-webrent"></img></a></h3>
		<div class="menu-admin">
		<a href="<%= users_path %>" class="<%= "active" if page == "users" %>"><span class="glyphicon glyphicon-user"></span> Tài khoản người dùng</a>
		<a href="#" class="<%= "active" if page == "webtypes" %>"><span class="glyphicon glyphicon-tasks"></span> Thể loại website</a>
		<a href="#" class="<%= "active" if page == "websites" %>"><span class="glyphicon glyphicon-list-alt"></span> Danh sách website</a>
		<a href="#" class="<%= "active" if page == "reports" %>"><span class="glyphicon glyphicon-stats"></span> Thống kê</a>
		<%= link_to raw("<i class='glyphicon glyphicon-off'></i> Đăng xuất"), signout_path, method: "delete" %>
		</div>
	</nav>
</div>

app/views/layouts/_navtabs.html.erb
<div class="sidebar-nav" style="padding-bottom: 25px;">
	<div class="well" style="width:250px;">
		<ul class="nav nav-list"> 
		  <li><a href="index" style="font-size:20px"><b><%= current_user.name %></b></a></li>
          <li><a href="#"><i class="glyphicon glyphicon-list" style="margin-right:5px"></i> Websites <span class="badge badge-primary">4</span></a></li>
          <li><a href="#"><i class="glyphicon glyphicon-shopping-cart" style="margin-right:5px"></i> Đơn hàng <span class="badge badge-primary">10</span></a></li>
          <li class="divider"></li>
		  <li><a href="#"><i class="glyphicon glyphicon-user" style="margin-right:5px"></i> Thông tin cá nhân</a></li>
		  <li><a href="#"><i class="glyphicon glyphicon-wrench" style="margin-right:5px"></i> Đổi mật khẩu</a></li>
		  <li><%= link_to raw("<i class='glyphicon glyphicon-share' style='margin-right:5px'></i> Đăng xuất"), signout_path, method: "delete" %></li>
		</ul>
	</div>
</div>

app/views/layouts/_popup_reset_password.html.erb
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3 class="modal-title"><b>Lấy lại mật khẩu</b></h3>
        <br>
        <p>Chúng tôi sẽ gửi cho bạn email làm thế nào để lấy lại mật khẩu.</p>
      </div>
      <div class="modal-body">
        <div id="alert-danger" style="display:block" class="alert alert-danger">
          Không có người dùng nào sử dụng địa chỉ email này. Mời nhập lại!
        </div>
        <div id="alert" style="display:none" class="alert alert-info">
          Chúng tôi đã gửi cho bạn một email để lấy lại mật khẩu.<br>
          Nếu bạn không nhận được email nào trong vòng một đến 2 giờ tới. Hãy kiểm tra thư mục spam trên email của bạn.
        </div>
        <div id="reset-password">
          <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="row">
              <div class="col-xs-8 col-sm-8 col-md-8">
                <input type="text" class="form-control" id="email" placeholder="Nhập vào địa chỉ email của bạn">
              </div>
              <div class="col-xs-2 col-sm-2 col-md-2">
                <%= link_to "Lấy lại mật khẩu", "#",class: "btn btn-webrent",id:"reset",remote:true %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Đóng</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script type="text/javascript">
jQuery(document).ready(function($) {
  $(".forgot").click(function(){
    $("#alert-danger").css("display","none")
    $("#alert").css("display","none")
    $("#reset-password").css("display","block")
    $('#myModal').modal({
      keyboard: false
    })
    $('#myModal').modal({
      backdrop: false
    })

  })

  $("#reset").click(function(){
    $email = $("#email").val()
    $.ajax({ type: "POST",   
      url: "<%=  forgot_password_path %>",   
      data: {email:$email} ,
      success : function(data)
      {
      }
    });
  })

});

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Webrent</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "jquery.gallery" %>
  <%= javascript_include_tag "component" %>
  <%= javascript_include_tag "classie" %>
  <%= javascript_include_tag "toucheffects" %>
  <%= javascript_include_tag "modernizr.custom.53451" %>
  <%= javascript_include_tag "scroll-startstop.events.jquery" %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= check_background() %>">
  <% page = check_page()[0] %>
  <%= render 'layouts/header' unless page == "administrators" %>
  <%= render 'layouts/menu' if page == "administrators" %>  
  <div class="container">
    <div class="col-md-11 col-md-offset-2">
      <% flash.each do |key, value| %>
      <% check_error = check_error(params[:controller],params[:action]) %>
      <% unless params[:commit] == "Đăng nhập" && params[:action] == "create" || check_error == true || params[:commit] == "Đăng ký" %>
      <div class="alert alert-<%= key %>" style="margin-top:20px"><%= value %></div>
      <% end %> 

      <% end %>
    </div>
    <%= yield %>
  </div>

  <%= yield(:homepage) %>
  

  <div id="contentPopup" style="display:none">    
    <%= yield(:popup) %>
  </div>

  <%= yield(:popup_reset) %>

  <%= yield(:upload_form) %>
  <%= render 'layouts/footer' unless page == "administrators" %>

</body>
</html>